# Generated by Django 2.1.7 on 2019-07-21 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atolye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atolye_baslik', models.CharField(max_length=150, verbose_name='Atölye Adı')),
                ('atolye_donem', models.CharField(max_length=100, verbose_name='Atölye Dönemi')),
                ('atolye_icerik', models.TextField(verbose_name='Atölye Açıklaması')),
                ('atolye_eklemetarihi', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atölye',
                'verbose_name_plural': 'Atölyeler',
                'ordering': ('-atolye_eklemetarihi',),
            },
        ),
        migrations.CreateModel(
            name='Burs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burs_baslik', models.CharField(max_length=150, verbose_name='Burs Başlığı')),
                ('burs_icerik', ckeditor.fields.RichTextField(verbose_name='Burs İçeriği')),
                ('burs_resim', models.ImageField(upload_to='', verbose_name='Burs Resmi 870x400')),
                ('burs_aktiflik', models.BooleanField(verbose_name='Burs Aktiflik Durumu')),
                ('burs_slug', models.SlugField(unique=True)),
                ('burs_yayintarihi', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Burs',
                'verbose_name_plural': 'Burslar',
                'ordering': ('-burs_yayintarihi',),
            },
        ),
        migrations.CreateModel(
            name='BursBasvuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bursbasvuru_isim', models.CharField(max_length=150, verbose_name='İsim-Soyisim')),
                ('bursbasvuru_email', models.CharField(max_length=150, verbose_name='Başvuran Email')),
                ('bursbasvuru_telefon', models.CharField(max_length=150, verbose_name='Başvuran Telefon')),
                ('bursbasvuru_basvurulanburs', models.CharField(max_length=150, verbose_name='Başvurulan Burs')),
                ('bursbasvuru_mesaj', models.TextField(verbose_name='Başvuran Mesajı')),
                ('bursbasvuru_tarih', models.DateField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
            ],
            options={
                'verbose_name': 'Burs Başvurusu',
                'verbose_name_plural': 'Burs Başvuruları',
                'ordering': ('-bursbasvuru_tarih',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150, verbose_name='İsim')),
                ('contact_email', models.CharField(max_length=150, verbose_name='Email Adresi')),
                ('contact_mesaj', models.TextField(verbose_name='İletişim Mesajı')),
                ('contact_tarih', models.DateField(auto_now_add=True, verbose_name='İletişim Talebi Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Talebi',
                'verbose_name_plural': 'İletişim Talepleri',
                'ordering': ('-contact_tarih',),
            },
        ),
        migrations.CreateModel(
            name='GonulluBasvuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonullu_isim', models.CharField(max_length=100, verbose_name='Gönüllü İsmi')),
                ('gonullu_email', models.CharField(max_length=150, verbose_name='Gönüllü Email Adresi')),
                ('gonullu_telefon', models.CharField(max_length=100, verbose_name='Gönüllü Telefon Numarası')),
                ('gonullu_calismaalani', models.CharField(max_length=100, verbose_name='Gönüllü Çalışma Alanı')),
                ('gonullu_baslamatarihi', models.CharField(max_length=100, verbose_name='Gönüllü Başlangıç Tarihi')),
                ('gonullu_mesaj', models.TextField(verbose_name='Gönüllü Mesajı')),
                ('gonullu_basvurutarihi', models.DateField(auto_now_add=True, verbose_name='Gönüllü Başvuru Tarihi')),
            ],
            options={
                'verbose_name': 'Gönüllü Başvurusu',
                'verbose_name_plural': 'Gönüllü Başvuruları',
                'ordering': ('-gonullu_basvurutarihi',),
            },
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_baslik', models.CharField(max_length=150, verbose_name='Proje Adı')),
                ('proje_yayintarihi', models.DateField(auto_now_add=True, verbose_name='Proje Tarihi')),
                ('proje_icerik', ckeditor.fields.RichTextField(verbose_name='Proje İçeriği')),
                ('proje_resim', models.ImageField(upload_to='', verbose_name='Proje Resmi 870x400')),
                ('proje_slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ('-proje_yayintarihi',),
            },
        ),
    ]
